#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Nov 19 16:48:14 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class ventana4(wx.Frame):
    def __init__(self, parent, informacion="",subtotal=0, informacion="", ):
        # begin wxGlade: ventana4.__init__
        
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 468))
        self.SetTitle("frame_3")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET", style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        sizer_2.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "_ _ _")
        sizer_2.Add(IbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        IbSubTotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:$")
        IbSubTotalTaquilla.SetForegroundColour(wx.Colour(35, 35, 142))
        grid_sizer_4.Add(IbSubTotalTaquilla, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        grid_sizer_4.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        IbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "_ _")
        sizer_2.Add(IbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        IbSubTotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:$")
        IbSubTotalDulceria.SetForegroundColour(wx.Colour(35, 35, 142))
        grid_sizer_2.Add(IbSubTotalDulceria, 0, 0, 0)

        IbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, "TOTAL: $")
        IbTotal.SetForegroundColour(wx.Colour(255, 0, 0))
        grid_sizer_2.Add(IbTotal, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "CANCELAR\n")
        self.btnCancelar.SetBitmap(wx.Bitmap("E:\\Cineplusaime3e\\limpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "FINALIZAR")
        self.btnFinalizar.SetBitmap(wx.Bitmap("E:\\Cineplusaime3e\\limpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        print("Event handler 'cancelarVenta' not implemented!")
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        print("Event handler 'finalizarVenta' not implemented!")
        event.Skip()

# end of class ventana4
class ventana3(wx.Frame):
    def __init__(self, parent, informacion="",subtotal=0):
        # begin wxGlade: ventana3.__init__
         kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1069, 658))
        self.SetTitle("Dulceria")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        
        #Variables de instanvia ventana3
        self.infoDulceria=""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal
    
        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_3.Add(self.spComboB, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        grid_sizer_12.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch")
        grid_sizer_12.Add(label_3, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_3.Add(bitmap_3, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_4.Add(self.spComboC, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        grid_sizer_13.Add(label_4, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Md")
        grid_sizer_13.Add(label_5, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo 2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_4.Add(bitmap_4, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_5.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_6.Add(self.spComboF, 0, 0, 0)

        grid_sizer_14 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_6.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        grid_sizer_14.Add(label_6, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G")
        grid_sizer_14.Add(label_7, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo 3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(bitmap_5, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitas.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(bitmap_6, 0, 0, 0)

        grid_sizer_15 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        grid_sizer_15.Add(label_8, 0, 0, 0)

        grid_sizer_17 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_15.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_17.Add(self.spPalomitasCh, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        grid_sizer_17.Add(label_9, 0, 0, 0)

        grid_sizer_18 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_15.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_18.Add(self.spPalomitasMd, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        grid_sizer_18.Add(label_10, 0, 0, 0)

        grid_sizer_19 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_15.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_19.Add(self.spPalomitasG, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        grid_sizer_19.Add(label_11, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refresco.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_9.Add(bitmap_7, 0, 0, 0)

        grid_sizer_16 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        grid_sizer_16.Add(label_12, 0, 0, 0)

        grid_sizer_20 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_16.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        grid_sizer_20.Add(label_13, 0, 0, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        grid_sizer_20.Add(label_14, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        grid_sizer_20.Add(label_15, 0, 0, 0)

        grid_sizer_21 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_16.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_21.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_21.Add(self.cmbSabor, 0, 0, 0)

        self.cmbCantidad = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_21.Add(self.cmbCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar\n")
        grid_sizer_21.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        ibProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:...")
        grid_sizer_10.Add(ibProductosAgregados, 0, 0, 0)

        grid_sizer_22 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_10.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria:")
        grid_sizer_22.Add(label_17, 0, 0, 0)

        IbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        IbSubtotal.SetForegroundColour(wx.Colour(255, 0, 0))
        grid_sizer_22.Add(IbSubtotal, 0, 0, 0)

        grid_sizer_11 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetBitmap(wx.Bitmap("E:\\Cineplusaime3e\\limpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetBitmap(wx.Bitmap("E:\\cineplus3e\\siguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.AgregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Basicos \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)           
        event.Skip()

    def calcularComboCuates(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Cuates \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*200
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Familiares \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasCh(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos PalomitasCh \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasMd(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*80
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos PalomitasMd \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasG(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*85
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos PalomitasG \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def AgregarRefrescos(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()
        subtotalrefrescos=0
        if tamanyo == "chico":
            subtotalrefrescos=numero*25
        elif tamanyo == "mediano":
            subtotalrefrescos=numero*40
        elif tamanyo =="grande":
            subtotalrefrescos=numero*60
        self.subtotalDulceria==self.subtotalDulceria+subtotalrefrescos
        self.lbSubtotal. SetLabel(f"$ {self.subtotalDulceria}")
        self.infoDulceria==self.infoDulceria + f" {numero} Refrescos {sabor} tamaño {tamanyo}\n" 
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>
       #Limpiamos las variables de instancia
       self.subtotalDulceria==0
       self.infoDulceria==""
       #Limpiamos los controles
       self.spComboB.SetValue(0)
       self.spComboC.SetValue(0)
       self.spComboF.SetValue(0)
       self.spPalomitasCh.SetValue(0)
       self.spPalomitasMd.SetValue(0)
       self.spPalomitasG.SetValue (0)
       self.spCantidad. SetValue(0)
       self.cmbSabor. SetSelection(wx.NOT_FOUND)
       self.cmbTamano. SetSelection (wx.NOT_FOUND)
       self.lbProductosAgregadosbProductosAgregados.SetLabel("---")
       self.lbsubtotal.SetLabel("$00.00")
    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        self.limpiarDulceria()
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmación de Dulceria.\n"
        f"¿Está seguro que desea adquirir?\n\n {self.infoDulceria}\n" 
        f"Subtotal Dulceria: $ {self.subtotalDulceria}" ,
        "Dulceria", style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal ()
        pregunta.Destroy()  # Cerramos el diálogo

        if respuesta == wx.ID_YES:
            #v4 = Ventana4(self, informacion=self.infoTaquilla, 
                        #subtotal=self.subtotalTaquilla, 
                        #informacion2=self.infoDulceria, 
                        #subtotal2=self.subtotalTaquilla)
            #v4.Show()
            self.limpiarDulceria()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarDulceria()
        event.Skip()

    def chico(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'chico' not implemented!")
        event.Skip()
    def mediano(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'mediano' not implemented!")
        event.Skip()
    def grande(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'grande' not implemented!")
        event.Skip()
    def pepsi(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'pepsi' not implemented!")
        event.Skip()
    def manzanita(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'manzanita' not implemented!")
        event.Skip()
    def AgregarRefrescos(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'AgregarRefrescos' not implemented!")
        event.Skip()
    def AgregarRefresco(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'AgregarRefresco' not implemented!")
        event.Skip()
# end of class ventana3

class Ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((493, 617))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(148, 255, 216))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\Cineplusaime3e\\logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Cooper Black"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\Cineplusaime3e\\logotipo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        lbPelicula = wx.StaticText(self.panel_1, wx.ID_ANY, "Pelicula:")
        lbPelicula.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(lbPelicula, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(lbSala, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        lbHorario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(lbHorario, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.NullBitmap)
        grid_sizer_6.Add(bitmap_3, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(4, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["F1", "Karate Kid", "Cars"], style=wx.CB_DROPDOWN)
        grid_sizer_7.Add(self.cmbPelicula, 0, wx.ALIGN_CENTER, 0)

        IbVersala = wx.StaticText(self.panel_1, wx.ID_ANY, "--")
        IbVersala.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_7.Add(IbVersala, 0, wx.ALIGN_CENTER_VERTICAL | wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_8.Add(self.rbHorario1, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_8.Add(self.rbHorario2, 0, wx.ALIGN_CENTER, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_8.Add(self.rbHorario3, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_8.Add((0, 0), 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_7.Add(self.panel_2, 1, wx.EXPAND, 0)

        bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\Cineplusaime3e\\imagenes\\pelicula3.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bmPelicula, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "BOLETOS")
        label_6.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Cooper Black"))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        lbAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos ($80) :")
        lbAdultos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(lbAdultos, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfAdultos.SetMinSize((113, 23))
        grid_sizer_3.Add(self.tfAdultos, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        lbMenores = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores ($70) :")
        lbMenores.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(lbMenores, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        grid_sizer_4.Add(self.tfMenores, 0, wx.ALIGN_CENTER, 0)

        lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        lbSubtotal.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbSubtotal, 0, wx.EXPAND, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar ")
        self.btnLimpiar.SetMinSize((110, 40))
        self.btnLimpiar.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("E:\\Cineplusaime3e\\limpiar.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Suiguiente")
        self.btnSiguiente.SetMinSize((110, 40))
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("E:\\cineplus3e\\siguiente.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        bitmap = wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: Ventana2.<event_handler>
        pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""

        print(f"Pelicula seleccioanda: {pelicula}")

        if pelicula == "F1":
            imagen="imagenes/pelicula1.png"
            sala="1"
            horario1="12:00"
            horario2="14:00"
            horario3="17:00"

        elif pelicula == "Karate Kid":
            imagen="imagenes/pelicula2.png"
            sala="2"
            horario1="13:00"
            horario2="16:00"
            horario3="18:00"

        elif pelicula == "Cars":
            imagen="imagenes/pelicula3.png"
            sala="3"
            horario1="14:00"
            horario2="17:00"
            horario3="19:00"

        self.cargar_imagen(imagen)
        self.lbVersala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula: {pelicula} \n Sala: {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: Ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.adultos=int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")

        except ValueError:
            wx.MessageBox("Por favor ingresa un número válido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: Ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos * 80) + subtotal_b
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")

        except ValueError:
            wx.MessageBox("Por favor ingresa un número váido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def limpiarValores_Campos(self):

        #Limpiar Variables de Instancia
        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        #Limpiar Campos
        self.cargar_imagen("logo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cmbPelicula.SetSelection(wx.NOT_FOUND)
        self.lbVersala.SetLabel("--")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbSubtotal.SetLabel("0")

    def limpiarTaquilla(self, event):  # wxGlade: Ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: Ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion} \n Adultos: {self.adultos}\n Menores de 12 años: {self.menores}"
        self.informacion = f"{self. informacion} \n Subtotal: {self.subtotal}"

        pregunta = wx.MessageDialog(
        self,
        f"Confirmación de Taquilla.\n"
        f"¿Está seguro que desea adquirir?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #Cerramos el dialogo

        if respuesta == wx.ID_YES:
            print(f"Venta de Taquilla realizada\n {self.informacion}")
            v3 = ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            #self.Hide
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

# end of class Ventana2

class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("Inicio de secion-CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("logotipo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 255, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        ibBienvenidos = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        ibBienvenidos.SetMinSize((132, 35))
        ibBienvenidos.SetForegroundColour(wx.Colour(0, 0, 0))
        ibBienvenidos.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(ibBienvenidos, 0, wx.EXPAND, 0)

        Iblogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\Cineplusaime3e\\logotipo.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(Iblogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        ibUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario", style=wx.ALIGN_CENTER_HORIZONTAL)
        ibUsuario.SetMinSize((445, 20))
        sizer_1.Add(ibUsuario, 0, 0, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        ibClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña", style=wx.ALIGN_CENTER_HORIZONTAL)
        ibClave.SetMinSize((445, 20))
        ibClave.SetForegroundColour(wx.Colour(0, 0, 0))
        sizer_1.Add(ibClave, 0, 0, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Narrow"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir\n")
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()

        if nombre == "aime" and clave == "321":
            print(f"¡Bienvenida,{nombre}! Acceso autorizado.")
            v2 = Ventana2(self)
            v2.Show()
            self.Hide()
        else:
            print("Acceso denegado.Usuario o clave incorrectos.")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        pregunta = wx.MessageDialog(self, "se cerrara la ventana,\n"\
        "¿Esta seguro que desea salir?", "Confirmar salida",style=wx.ICON_QUESTION)
         
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print("¡Bye!")
            self.Close()
        event.Skip()

# end of class ventana1

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
